fix java options (previous edit) and find java if not in path.

diff --git a/bin/voms-proxy-init b/bin/voms-proxy-init
--- a/bin/voms-proxy-init
+++ b/bin/voms-proxy-init
@@ -11,6 +11,21 @@ if [ "$1" = "-v" ]; then
   shift
   verbose=1
 fi
+
+# find java
+if type -p java > /dev/null; then
+  java=java
+else
+  for id in 38 42; do  # $PROGRAMFILES and $ProgramFiles(x86)
+    java=$(ls -1vr "$(cygpath -F $id)"/Java/*/bin/java.exe | head -n1)
+    [ -n "$java" ] && break
+  done
+  if [ -z "$java" ]; then
+    echo "$prog: could not locate java" >&2
+    java=java   # try anyway
+  fi
+fi
+
 dir=$(readlink -e "$0")
 dir=$(dirname "$dir")
 test $(basename "$dir") = "bin" && dir=$(dirname "$dir")
@@ -20,7 +35,7 @@ VOMSCLIENTS_CP=$(set +f; for f in "$VOMSCLIENTS_LIBS"/*.jar; do cygpath -wa "$f"
 # the class implementing voms-proxy-init etc
 VOMSCLIENTS_CLASS="org.italiangrid.voms.clients.$class"
 # JVM options
-VOMS_CLIENTS_JAVA_OPTIONS="-Xmx16m"
+VOMS_CLIENTS_JAVA_OPTIONS="-XX:+UseSerialGC -Xmx16m"
 
 setenv() {
   if [ -n "${!1}" ]; then
@@ -66,4 +81,4 @@ fi
 test $verbose -ne 0 && set -x
 
 # Run command with java
-java $VOMS_CLIENTS_JAVA_OPTIONS -cp "$VOMSCLIENTS_CP" "$VOMSCLIENTS_CLASS" "${opts[@]}" "$@"
+"$java" $VOMS_CLIENTS_JAVA_OPTIONS -cp "$VOMSCLIENTS_CP" "$VOMSCLIENTS_CLASS" "${opts[@]}" "$@"
